<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WisataSeeder extends Seeder
{
    public function run(): void
    {
        $wisatas = [
            [
                'no' => 1,
                'nama_wisata' => 'Candi Borobudur',
                'jam_operasional' => '06.00 - 17.00 WIB',
                'harga_tiket' => 'Rp 50.000 (Dewasa) / Rp 25.000 (Anak)',
                'fasilitas' => 'Parkir, Toilet, Mushola, Kios Souvenir, Pemandu Wisata, Warung Makan, Lift Difabel',
                'lokasi' => 'Jl. Badrawati, Borobudur, Magelang (dekat Yogyakarta)',
                'deskripsi' => 'Candi Buddha terbesar di dunia yang dibangun pada abad ke-8, merupakan Warisan Budaya UNESCO. Memiliki 504 patung Buddha dan 2.672 panel relief yang menceritakan kisah kehidupan Buddha.',
                'rating' => 4.8,
                'latitude' => -7.6079,
                'longitude' => 110.2038,
                'kategori' => 'Candi & Sejarah',
            ],
            [
                'no' => 2,
                'nama_wisata' => 'Candi Prambanan',
                'jam_operasional' => '06.00 - 17.00 WIB',
                'harga_tiket' => 'Rp 50.000 (Dewasa) / Rp 25.000 (Anak)',
                'fasilitas' => 'Parkir, Toilet, Mushola, Kios Souvenir, Museum, Pemandu Wisata, Restoran',
                'lokasi' => 'Jl. Raya Solo - Yogyakarta No.16, Kranggan, Bokoharjo, Prambanan, Sleman',
                'deskripsi' => 'Kompleks candi Hindu terbesar di Indonesia yang didedikasikan untuk Trimurti (Brahma, Wisnu, Siwa). Dibangun pada abad ke-9 dan merupakan Warisan Budaya UNESCO dengan ketinggian candi utama 47 meter.',
                'rating' => 4.7,
                'latitude' => -7.7520,
                'longitude' => 110.4914,
                'kategori' => 'Candi & Sejarah',
            ],
            [
                'no' => 3,
                'nama_wisata' => 'Keraton Yogyakarta',
                'jam_operasional' => '08.00 - 14.00 WIB (Senin-Minggu, tutup Jumat)',
                'harga_tiket' => 'Rp 15.000 (Umum) / Rp 5.000 (Pelajar)',
                'fasilitas' => 'Parkir, Toilet, Pemandu Wisata, Museum, Toko Batik, Pertunjukan Seni Budaya',
                'lokasi' => 'Jl. Rotowijayan Blok No.1, Panembahan, Kraton, Yogyakarta',
                'deskripsi' => 'Istana resmi Kesultanan Yogyakarta yang dibangun Sultan Hamengkubuwono I pada tahun 1755. Menjadi pusat kebudayaan Jawa dengan koleksi artefak kerajaan, gamelan, dan pertunjukan wayang.',
                'rating' => 4.6,
                'latitude' => -7.8054,
                'longitude' => 110.3641,
                'kategori' => 'Budaya & Sejarah',
            ],
            [
                'no' => 4,
                'nama_wisata' => 'Pantai Parangtritis',
                'jam_operasional' => '24 Jam (Aktif 06.00 - 18.00 WIB)',
                'harga_tiket' => 'Rp 10.000 (Weekday) / Rp 15.000 (Weekend)',
                'fasilitas' => 'Parkir, Toilet, Warung Makan, Penyewaan ATV, Penyewaan Kuda, Penginapan, Mushola',
                'lokasi' => 'Parangtritis, Kretek, Bantul, Yogyakarta (27 km dari kota)',
                'deskripsi' => 'Pantai legendaris di selatan Yogyakarta yang terkenal dengan ombak besar dan pasir hitam vulkanik. Menjadi lokasi mitos Ratu Pantai Selatan dan sering digunakan untuk upacara adat Jawa.',
                'rating' => 4.4,
                'latitude' => -8.0229,
                'longitude' => 110.3312,
                'kategori' => 'Pantai & Alam',
            ],
            [
                'no' => 5,
                'nama_wisata' => 'Taman Sari Water Castle',
                'jam_operasional' => '08.00 - 14.00 WIB',
                'harga_tiket' => 'Rp 15.000 (Umum) / Rp 5.000 (Pelajar)',
                'fasilitas' => 'Parkir, Toilet, Pemandu Wisata, Kios Souvenir, Galeri Batik',
                'lokasi' => 'Jl. Tamansari No.1, Patehan, Kraton, Yogyakarta',
                'deskripsi' => 'Bekas taman kerajaan Keraton Yogyakarta yang dibangun tahun 1758. Kompleks ini memiliki kolam pemandian kerajaan, terowongan bawah tanah, dan menara pengawas yang menjadi simbol kemewahan Sultan.',
                'rating' => 4.5,
                'latitude' => -7.8100,
                'longitude' => 110.3590,
                'kategori' => 'Budaya & Sejarah',
            ],
            [
                'no' => 6,
                'nama_wisata' => 'Malioboro',
                'jam_operasional' => '08.00 - 22.00 WIB',
                'harga_tiket' => 'Gratis (Kawasan Publik)',
                'fasilitas' => 'Parkir, Toilet Umum, ATM, Hotel, Restoran, Kios Oleh-oleh, Becak Wisata, Halte TransJogja',
                'lokasi' => 'Jl. Malioboro, Gedongtengen, Yogyakarta',
                'deskripsi' => 'Jalan ikonik Yogyakarta yang menjadi pusat perbelanjaan dan wisata budaya. Terkenal dengan pedagang batik, kerajinan perak, oleh-oleh khas Jogja, dan pertunjukan seni jalanan.',
                'rating' => 4.5,
                'latitude' => -7.7928,
                'longitude' => 110.3656,
                'kategori' => 'Belanja & Kuliner',
            ],
            [
                'no' => 7,
                'nama_wisata' => 'Gunung Merapi',
                'jam_operasional' => '05.00 - 17.00 WIB',
                'harga_tiket' => 'Rp 10.000 (Masuk Area) + Rp 450.000 (Jeep Tour)',
                'fasilitas' => 'Parkir, Toilet, Warung Makan, Penyewaan Jeep, Museum Sisa Hartaku, Pemandu Wisata',
                'lokasi' => 'Hargobinangun, Pakem, Sleman, Yogyakarta',
                'deskripsi' => 'Gunung berapi aktif paling berbahaya di Indonesia dengan ketinggian 2.930 mdpl. Menawarkan wisata jeep off-road melewati desa-desa terdampak letusan 2010, Kali Kuning, dan Museum Sisa Hartaku.',
                'rating' => 4.7,
                'latitude' => -7.5407,
                'longitude' => 110.4457,
                'kategori' => 'Alam & Petualangan',
            ],
            [
                'no' => 8,
                'nama_wisata' => 'Pantai Indrayanti',
                'jam_operasional' => '06.00 - 18.00 WIB',
                'harga_tiket' => 'Rp 10.000 per orang',
                'fasilitas' => 'Parkir, Toilet, Warung Makan, Restoran Seafood, Gazebo, Penginapan, Snorkeling',
                'lokasi' => 'Tepus, Gunung Kidul, Yogyakarta (70 km dari kota)',
                'deskripsi' => 'Pantai berpasir putih bersih dengan air biru jernih di kawasan Gunung Kidul. Terkenal dengan deretan restoran seafood di tepi pantai, formasi batu karang yang indah, dan suasana yang lebih tenang.',
                'rating' => 4.5,
                'latitude' => -8.1561,
                'longitude' => 110.6313,
                'kategori' => 'Pantai & Alam',
            ],
            [
                'no' => 9,
                'nama_wisata' => 'Kebun Binatang Gembira Loka',
                'jam_operasional' => '08.00 - 16.00 WIB',
                'harga_tiket' => 'Rp 60.000 (Dewasa) / Rp 50.000 (Anak < 3 tahun gratis)',
                'fasilitas' => 'Parkir, Toilet, Mushola, Restoran, Wahana Bermain Anak, Toko Souvenir, Area Selfie',
                'lokasi' => 'Jl. Kebun Raya No.2, Rejowinangun, Kotagede, Yogyakarta',
                'deskripsi' => 'Kebun binatang terbesar dan tertua di Yogyakarta yang berdiri sejak 1953. Memiliki lebih dari 200 spesies hewan dengan koleksi satwa langka seperti harimau Sumatera, orangutan, dan komodo.',
                'rating' => 4.3,
                'latitude' => -7.8227,
                'longitude' => 110.3878,
                'kategori' => 'Hiburan & Keluarga',
            ],
            [
                'no' => 10,
                'nama_wisata' => 'Bukit Bintang Yogyakarta',
                'jam_operasional' => '17.00 - 23.00 WIB (terbaik malam hari)',
                'harga_tiket' => 'Gratis (Biaya parkir Rp 5.000)',
                'fasilitas' => 'Parkir, Toilet, Warung Makan, Lesehan, Kafe dengan View Kota',
                'lokasi' => 'Jl. Wonosari KM 16, Patuk, Gunung Kidul, Yogyakarta',
                'deskripsi' => 'Spot terbaik untuk melihat pemandangan kota Yogyakarta dari ketinggian, terutama saat malam hari. Deretan warung lesehan dan kafe menyajikan hidangan sambil menikmati gemerlap lampu kota.',
                'rating' => 4.4,
                'latitude' => -7.8500,
                'longitude' => 110.4600,
                'kategori' => 'Alam & Petualangan',
            ],
            [
                'no' => 11,
                'nama_wisata' => 'Candi Ratu Boko',
                'jam_operasional' => '06.00 - 17.00 WIB',
                'harga_tiket' => 'Rp 40.000 (Dewasa) / Rp 20.000 (Anak)',
                'fasilitas' => 'Parkir, Toilet, Restoran, Pemandu Wisata, Area Sunset Terbaik, Kios Souvenir',
                'lokasi' => 'Jl. Raya Piyungan - Prambanan, Gatak, Bokoharjo, Prambanan, Sleman',
                'deskripsi' => 'Reruntuhan kompleks keraton kuno di atas bukit dengan ketinggian 196 mdpl. Terkenal sebagai spot sunset terbaik di Yogyakarta dengan latar belakang Candi Prambanan dan pemandangan kota spektakuler.',
                'rating' => 4.6,
                'latitude' => -7.7704,
                'longitude' => 110.4889,
                'kategori' => 'Candi & Sejarah',
            ],
            [
                'no' => 12,
                'nama_wisata' => 'Pantai Baron',
                'jam_operasional' => '06.00 - 18.00 WIB',
                'harga_tiket' => 'Rp 10.000 per orang',
                'fasilitas' => 'Parkir, Toilet, Warung Makan, Pasar Ikan, Dermaga Nelayan, Mushola',
                'lokasi' => 'Baron, Kemadang, Tanjungsari, Gunung Kidul, Yogyakarta',
                'deskripsi' => 'Pantai dengan pasir coklat yang dikelilingi tebing karst hijau. Terkenal sebagai pusat pelelangan ikan terbesar di Gunung Kidul dengan sumber air tawar alami yang mengalir langsung ke laut.',
                'rating' => 4.3,
                'latitude' => -8.1296,
                'longitude' => 110.5358,
                'kategori' => 'Pantai & Alam',
            ],
            [
                'no' => 13,
                'nama_wisata' => 'Museum Ullen Sentalu',
                'jam_operasional' => '08.30 - 16.00 WIB (Senin tutup)',
                'harga_tiket' => 'Rp 50.000 (Umum) / Rp 25.000 (Pelajar)',
                'fasilitas' => 'Parkir, Toilet, Café Belanda, Pemandu Wajib, Toko Batik, Taman Tropis',
                'lokasi' => 'Jl. Boyong No.KM 25, Kaliurang, Pakem, Sleman, Yogyakarta',
                'deskripsi' => 'Museum budaya Jawa terbaik yang menyimpan koleksi lukisan, batik, dan artefak Keraton Yogyakarta dan Surakarta. Terletak di lereng Gunung Merapi dengan arsitektur unik dan taman tropis yang asri.',
                'rating' => 4.8,
                'latitude' => -7.6025,
                'longitude' => 110.4216,
                'kategori' => 'Budaya & Sejarah',
            ],
            [
                'no' => 14,
                'nama_wisata' => 'Hutan Pinus Mangunan',
                'jam_operasional' => '06.00 - 17.00 WIB',
                'harga_tiket' => 'Rp 5.000 per orang',
                'fasilitas' => 'Parkir, Toilet, Warung Makan, Spot Foto Instagramable, Ayunan, Hammock',
                'lokasi' => 'Mangunan, Dlingo, Bantul, Yogyakarta',
                'deskripsi' => 'Kawasan hutan pinus yang menjadi surga bagi para pecinta fotografi. Pohon-pohon pinus menjulang tinggi menciptakan suasana mistis dan romantis, dengan berbagai spot foto menarik seperti ayunan dan hammock.',
                'rating' => 4.4,
                'latitude' => -7.9195,
                'longitude' => 110.4248,
                'kategori' => 'Alam & Petualangan',
            ],
            [
                'no' => 15,
                'nama_wisata' => 'Kalibiru National Park',
                'jam_operasional' => '06.00 - 17.30 WIB',
                'harga_tiket' => 'Rp 10.000 (Masuk) + Rp 10.000 (Foto di Spot)',
                'fasilitas' => 'Parkir, Toilet, Warung Makan, Spot Foto, Flying Fox, Camping Ground, Outbound',
                'lokasi' => 'Kalibiru, Hargowilis, Kokap, Kulon Progo, Yogyakarta',
                'deskripsi' => 'Spot wisata alam viral dengan pemandangan Waduk Sermo dan perbukitan hijau dari ketinggian. Terkenal dengan foto ikonik berdiri di atas pohon dengan latar waduk. Menjadi salah satu destinasi paling hits di Yogyakarta.',
                'rating' => 4.5,
                'latitude' => -7.8102,
                'longitude' => 110.1312,
                'kategori' => 'Alam & Petualangan',
            ],
        ];

        foreach ($wisatas as $wisata) {
            DB::table('wisatas')->insert(array_merge($wisata, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
